
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRkJqdHE4empJeE13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01EVXdPVFUwTVRCYUZ3MHpOakEzTURJd09UVTVNVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUROWk5rUVkzZWxyZ1V5R2dPcTM4OG9UNkRnODg4VHJtelNiMW1lV00rdFBLSm5HUlkybkNKS3hocUUKZGNCcExNSXBLTm5XWE5pYW43b1RBc01XRXN3ZEJpUlBOeWFTYkg1MUk0WkdLOGhSa0loc2l5R2VndldiWkpWRwo5Rlc2eTRyUzhjNHBJZEIvVHZPdXpsdjdvZFBiWmV6YU5tWDJUQlV0MDJ5L1N4Q3dENFVnRDRaNHdVNFJBbTB1CkZjYWcrKy8wZEFsdGsxUDBiSjJCVEFPWkx4RVhQOXJ3cUNiV1lBK1JPOWF0Vms1OGZMQi9LMUJKVnh2ZzJid0kKNmJPYU1OSkg5YmMzM01vd3JkSWpobFQyRnlvR3BTelcvckJVZHdDSVVMNno3OU5aVFpKekNXZkpJNHgyUEhMUwo2S0duNzRxNFRQWXRYWStnYWRUbG9sTW5BRFhGQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRcHZXOTNtRWkyN1pFRys0bnhsZG56bjJkcnZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3BuNi9GN1RNVQo3MTVxUG42ODY5bENwTVlSR2hxZXhJS2ZRU1laYTJ0Nzd2NjdYWmVRQ3EyNjRkODBWNDJoMnBFc2hXQVFxenJuCjUrYTBQWTJFN0QyT3hyQ2gwZ0lHOVJiejBGV3JaTzU0ODhLc1BObEFVZi9meEdMRGYrQXpCN2I3ZmN4YWs5bXEKdklYNDdpeFRUSE5hdlZ3di9MOEl1c0JycFJWd1VEVzNJbVp5TFhUeFNBb2lHZHp6YlJaWFFXdk5DSEVIdXh6NQpEcjNYUGpLeTZKSDl3anpsdW5tbmR2TnV0bHdYbC9CNnJzYThMWTY4M1hCQ2FvNFd2aDh4RWVmM0c3T3p5cFhJCkI0SjdYK2hMR2xMRUt3eGdocUs5YTc0eXhRSStCUmZ4T1JMcUsrMXhtTngrYXBEK0hHQnNjZElveEpzODg0S3kKYTJnU1daaVRkVkNmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://03dfca81-32da-491d-996c-f8d57ec45113.eu-central-3-gw.linodelke.net:443
  name: lke626242

users:
- name: lke626242-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjRTU0hWR2gtSzByc2ljYTBmZWhlRUdlQUdZazV4TXlJaEI3TllGdV8zdnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tOHNoZDUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYjU0YjlkZDMtZmY0YS00NjEyLWJkZmMtNzE1N2YwMzEyNzQ5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.gK1Gm86hyxb6pyv1sNtqJhpUb2zw6ojA71ITsta6uO2YPr0fFxbUeo7Qm1oGQUFh4eMSTUhtOClKCeiLZ5MHiOuUZRHPeCMQ-sgv0yh4xt_hzvBRggVFJO-5N0qEjhJdxymT3rm1_DiPJ4SsWbp3_JFtBhHP2qg-nvg4TpZdgP3xmqn10kO4NJ8kpeIsM6C4cA_Hx_Ssf7ipF-0nXLcN0ZCg8bl0k-FOg_cGb-KlgeEdQGT6JudUBLM8bstZPpe_u1_kzH_rH-X45M5fqY2eGUFZLY9pmvTTWOg0-_mOo0HRgAFB4vXJ8tO082XxYEYAzRiLKJGAqUi6ro0qjc_pZw

contexts:
- context:
    cluster: lke626242
    namespace: default
    user: lke626242-admin
  name: lke626242-ctx

current-context: lke626242-ctx
